--created by Discord \ Walrus, art generated by Dall-E2 AI
--終わりの存在者
local s,id,o=GetID()
function s.initial_effect(c)
	--If there are at least 5 banished DARK monsters, you can Special Summon this card (from your hand).
	local e1=Effect.CreateEffect(c)
	e1:SetType(EFFECT_TYPE_FIELD)
	e1:SetCode(EFFECT_SPSUMMON_PROC)
	e1:SetRange(LOCATION_HAND)
	e1:SetProperty(EFFECT_FLAG_CANNOT_DISABLE+EFFECT_FLAG_UNCOPYABLE)
	e1:SetCondition(s.spcon)
	c:RegisterEffect(e1)
	--You can only use each effect of "The Being of the End" once per turn.
	--When your opponent activates a card or effect (Quick Effect): You can banish 1 DARK monster from your hand; negate the activation, and if you do, banish it.
e2
	--During your Main Phase, if this card is in your GY: You can shuffle as many of your banished cards into the Deck as possible; banish this card face-down, and if you do, draw 1 card.
e3
end
function s.()
end
function s.()
end
