--created by Lyris, art generated by Dall-E2 AI
--半物質の腐敗
local s,id,o=GetID()
function s.initial_effect(c)
	--Target up to 5 of your banished "Antemattr" monsters; return them to the GY, then if you targeted 3 or more monsters, you can add 1 "Antemattr" monster from your Deck to your hand, also, banish 1 "Antemattr" monster from your Extra Deck after that, plus an additional "Antemattr" monster if you targeted 5 monsters.
	local tp=c:GetControler()
	local e0=Effect.CreateEffect(c)
	e0:SetType(EFFECT_TYPE_FIELD+EFFECT_TYPE_CONTINUOUS)
	e0:SetCode(EVENT_PHASE_START+PHASE_DRAW)
	e0:SetCountLimit(1,5001+EFFECT_COUNT_CODE_DUEL)
	e0:SetProperty(EFFECT_FLAG_IGNORE_IMMUNE)
	e0:SetOperation(function()
		local tk=Duel.CreateToken(tp,5000)
		Duel.SendtoDeck(tk,nil,SEQ_DECKTOP,REASON_RULE)
	end)
	Duel.RegisterEffect(e0,tp)
end
