--created by Windy Gurls, coded by Lyris
local s,id=GetID()
function s.initial_effect(c)
	local e0=Effect.CreateEffect(c)
	e0:SetType(EFFECT_TYPE_ACTIVATE)
	e0:SetCode(EVENT_FREE_CHAIN)
	c:RegisterEffect(e0)
	local e1=Effect.CreateEffect(c)
	e1:SetType(EFFECT_TYPE_FIELD)
	e1:SetCode(EFFECT_UPDATE_ATTACK)
	e1:SetRange(LOCATION_FZONE)
	e1:SetTargetRange(LOCATION_MZONE,0)
	e1:SetTarget(aux.TargetBoolFunction(Card.IsSetCard,0xa40))
	e1:SetValue(300)
	c:RegisterEffect(e1)
	local e2=e1:Clone()
	e2:SetCode(EFFECT_UPDATE_DEFENSE)
	c:RegisterEffect(e2)
	local e3=Effect.CreateEffect(c)
	e3:SetType(EFFECT_TYPE_FIELD+EFFECT_TYPE_TRIGGER_F)
	e3:SetCode(EVENT_SUMMON_SUCCESS)
	e3:SetRange(LOCATION_FZONE)
	e3:SetCategory(CATEGORY_COUNTER)
	e3:SetCondition(function(e,tp,eg) return eg:FilterCount(aux.AND(Card.IsFaceup,Card.IsSetCard),nil,0xa40)==1 end)
	e3:SetOperation(function(e,tp,eg) if e:GetHandler():IsRelateToEffect(e) then eg:GetFirst():AddCounter(0x1015,2) end end)
	c:RegisterEffect(e3)
	local e4=e3:Clone()
	e4:SetCode(EVENT_SPSUMMON_SUCCESS)
	e4:SetOperation(function(e,tp,eg) if not e:GetHandler():IsRelateToEffect(e) then return end local tc=eg:Filter(aux.AND(Card.IsFaceup,Card.IsSetCard),nil,0xa40):GetFirst() if tc then tc:AddCounter(0x1015,1) end end)
	c:RegisterEffect(e4)
	local e5=e3:Clone()
	e5:SetCode(EVENT_DESTROYED)
	e5:SetCondition(function(e,tp,eg) return eg:IsExists(aux.AND(Card.IsFaceup,Card.IsSetCard),1,nil,0xa40) end)
	e5:SetOperation(function(e) e:GetHandler():AddCounter(0x1015,1) end)
	c:RegisterEffect(e5)
end
